from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    HRUserViewSet, 
    VisitorViewSet, 
    VisitRequestViewSet, 
    VisitorCardViewSet,
    visitor_registration,
    register_visitor,
    search_visitors,
    ajax_password_reset,
    export_visitors_excel,
    export_hos_visitors_excel,
    registration_user_login_view,
    registration_users_list,
    add_registration_user,
    delete_registration_user,
    hos_dashboard_view,
    hos_login_view,
    hos_password_reset,
    hos_password_reset_done,
    hos_password_reset_confirm,
    hos_password_reset_complete,
    registration_logout_view,
    hos_logout_view,
    print_card_dashboard,
    print_card_step2,
    mark_cards_printed,
    clear_print_session,
    delete_unprinted_visit_request,
    upload_visitor_photo,
    checkout_visitor,
    checkin_visitor,
    checkout_page,
    checked_in_visitors,
    manual_checkout_visitor,
)
from django.contrib.auth import views as auth_views

router = DefaultRouter()
router.register(r'hr-users', HRUserViewSet)
router.register(r'visitors', VisitorViewSet)
router.register(r'visit-requests', VisitRequestViewSet)
router.register(r'visitor-cards', VisitorCardViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('register/', visitor_registration, name='visitor-registration'),
    path('register_visitor/', register_visitor, name='register-visitor-api'),
    path('search_visitors/', search_visitors, name='search-visitors-api'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path('ajax/password_reset/', ajax_password_reset, name='ajax_password_reset'),
    path('export-visitors-excel/', export_visitors_excel, name='export_visitors_excel'),
    path('export-hos-visitors-excel/', export_hos_visitors_excel, name='export_hos_visitors_excel'),
    path('registration-login/', registration_user_login_view, name='registration-login'),
    path('registration-users-list/', registration_users_list, name='registration-users-list'),
    path('add-registration-user/', add_registration_user, name='add-registration-user'),
    path('delete-registration-user/', delete_registration_user, name='delete-registration-user'),
    path('hos-dashboard/', hos_dashboard_view, name='hos-dashboard'),
    path('hos-login/', hos_login_view, name='hos-login'),
    path('hos-password-reset/', hos_password_reset, name='hos-password-reset'),
    path('hos-password-reset-done/', hos_password_reset_done, name='hos-password-reset-done'),
    path('hos-reset/<uidb64>/<token>/', hos_password_reset_confirm, name='hos-password-reset-confirm'),
    path('hos-reset/done/', hos_password_reset_complete, name='hos-password-reset-complete'),
    path('registration-logout/', registration_logout_view, name='registration-logout'),
    path('hos-logout/', hos_logout_view, name='hos-logout'),
    path('print-card/', print_card_dashboard, name='print_card_dashboard'),
    path('print-card/step-2/', print_card_step2, name='print_card_step2'),
    path('print-card/mark-printed/', mark_cards_printed, name='mark_cards_printed'),
    path('print-card/clear-session/', clear_print_session, name='clear_print_session'),
    path('print-card/delete/<int:visit_id>/', delete_unprinted_visit_request, name='delete_unprinted_visit_request'),
    path('visitors/<int:visitor_id>/upload-photo/', upload_visitor_photo, name='upload_visitor_photo'),
    path('checkout/', checkout_visitor, name='checkout_visitor'),
    path('checkin/', checkin_visitor, name='checkin_visitor'),
    path('checkout-page/', checkout_page, name='checkout_page'),
    path('checked-in-visitors/', checked_in_visitors, name='checked_in_visitors'),
    path('manual-checkout/', manual_checkout_visitor, name='manual_checkout_visitor'),
] 