# Generated by Django 5.1.6 on 2025-06-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0002_visitor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='allow_laptop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='allow_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
