# Generated by Django 5.1.6 on 2025-06-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0004_alter_visitor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='other_purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
