# Generated by Django 5.1.6 on 2025-07-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0005_visitrequest_other_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='requestedByEmployee',
            field=models.BooleanField(default=False),
        ),
    ]
