# Generated by Django 5.1.6 on 2025-07-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0006_visitrequest_requestedbyemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='hruser',
            name='user_type',
            field=models.CharField(choices=[('HR', 'HR'), ('REGISTRATION', 'Registration')], default='HR', max_length=20),
        ),
    ]
