# Generated by Django 5.1.6 on 2025-07-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0007_hruser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='reference_employee_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='reference_employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='reference_purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
