# Generated by Django 5.1.6 on 2025-07-04 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0008_visitrequest_reference_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
