# Generated by Django 5.2.4 on 2025-07-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0009_visitrequest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorcard',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_qrcodes/'),
        ),
    ]
