# Generated by Django 5.1.6 on 2025-07-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0010_visitorcard_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorcard',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
