# Generated by Django 5.2.4 on 2025-07-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0011_visitorcard_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
