# Generated by Django 5.2.4 on 2025-07-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0012_visitrequest_checkin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
