# Generated by Django 5.2.4 on 2025-07-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0013_visitrequest_checkout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='checkout_by_hr',
            field=models.BooleanField(default=False),
        ),
    ]
