# Generated by Django 5.2.4 on 2025-07-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0016_clean_remaining_duplicates'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
