# Generated by Django 5.2.4 on 2025-07-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0017_visitrequest_valid_upto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrequest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
