# Generated by Django 5.2.4 on 2025-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0020_migrate_old_checkin_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='overdue_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
