# Generated by Django 5.2.4 on 2025-08-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapi', '0021_visitrequest_overdue_notification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
